name: Build & Deploy Next.js to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write        # allow Pages deployment
      contents: read      # to checkout your repo
      id-token: write     # for Pages action auth

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build static site
        run: npm run build  # Next.js v14+ will emit out/ by virtue of output:'export'

      - name: Upload static files
        uses: actions/upload-pages-artifact@v3
        with:
          path: out          # package everything under out/ for deployment :contentReference[oaicite:1]{index=1}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
